# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_on', '-created_on'],
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(db_index=True, max_length=100)),
                ('recipients', models.CharField(db_index=True, max_length=255)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('headers', models.TextField()),
                ('received_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RejectedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(db_index=True, max_length=100)),
                ('recipients', models.CharField(db_index=True, max_length=255)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('headers', models.TextField()),
                ('received_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_on'],
                'abstract': False,
            },
        ),
    ]
