# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160511_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RejectedEmail',
        ),
        migrations.AlterField(
            model_name='incomingemail',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='incomingemail',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
